In [55]:
import numpy as np
import pandas as pd

from collections import defaultdict
from Bio import SeqIO

In [56]:
import numpy as np

def filter_outliers(data, k = 1.5, return_idx = False, method = 'iqr'):
    """Remove outliers outside [Q1 - k*IQR, Q3 + k*IQR]."""
    data = np.asarray(data)
    q1, q3 = np.percentile(data, [25, 75])
    iqr = q3 - q1
    lower, upper = q1 - k * iqr, q3 + k * iqr
    mask = (data >= lower) & (data <= upper)
    if return_idx:
        return np.where(mask)[0], data[mask]
    else:
        return data[mask]

Preprocess CAR entries from InterPro DB
----------------------------------------

In [81]:
fasta_path = 'car_interpro.fasta'

seq_to_records = defaultdict(list)

for record in SeqIO.parse(fasta_path, "fasta"):
    desc = record.description.split('|')
    uniprot_id = desc[0]
    is_reviewed = desc[1]
    function = desc[2]
    tax_id = desc[3]
    seq = str(record.seq)  # cast to str so it is hashable as a dict key
    
    seq_to_records[seq].append((uniprot_id, is_reviewed, function, tax_id))

# Build DataFrame: one row per unique sequence
rows = []
for seq, members in seq_to_records.items():
    uniprot_ids = [m[0] for m in members]
    
    reviewed_ids = [uid for uid, status, _, _ in members if status == 'reviewed']
    is_reviewed = f"reviewed ({','.join(reviewed_ids)})" if reviewed_ids else 'unreviewed'
    
    rows.append({
        'uniprot_id': ';'.join(uniprot_ids),
        'is_reviewed': is_reviewed,
        'function': ';'.join(set(m[2] for m in members)),
        'tax_id': ';'.join(m[3] for m in members),
        'length': len(seq),
        'sequence': seq,
    })

df_interpro = pd.DataFrame(rows)

print(f'Redundace: {len(list(SeqIO.parse(fasta_path, "fasta")))}, None-redundace: {len(df_interpro)}')
df_interpro

Redundace: 1026, None-redundace: 986

,uniprot_id,is_reviewed,function,tax_id,length,sequence
0,A0A010YLP6,unreviewed,Carrier domain-containing protein,taxID:927661,1152,MTHTDQGDVTTVAERRALLLEQDEQFASAVPDDHVTALVRQPTMSL...
1,A0A024JSK2,unreviewed,Carboxylic acid reductase,taxID:47839,1188,MTTDMKRENGTNSTTKATPRERVAERIRRVEATDEQYRNAKPDQAL...
2,A0A024JWI0,unreviewed,Carboxylic acid reductase,taxID:47839,1162,MSTTTREERLERRIENLTATDPQFAAAKPDPAVVEALEQPGLQLPQ...
3,A0A024JZE3,unreviewed,Carboxylic acid reductase,taxID:47839,1165,MAFVGRSDVKDPGAQQDQWERLARRRERLYAEDAQFAATRPDEQIA...
4,A0A024JZE8,unreviewed,Carboxylic acid reductase,taxID:47839,1182,MTSGSLRDIHLAEPGDNRDERTAQRVAELFDNDPQFRAAAPLPDVI...
...,...,...,...,...,...,...
981,X8CEN6,unreviewed,Carboxylic acid reductase,taxID:1299331,1162,MAATDEQFRNAQPDLSLQQAARQPGLRLPQILELFVEGYADRPAVG...
982,X8CIS2,unreviewed,Carboxylic acid reductase,taxID:1299331,1072,MSTAIHDENLDRRIEELIANDPQFAAARPDPAITAATEAPGLRLPQ...
983,X8DPU6,unreviewed,Carboxylic acid reductase,taxID:1299321,1183,MTIDATADNTKEARRQRLGDRVRRLFTEDEQFRAAKPDTAVDAAVA...
984,X8DT62,unreviewed,Carrier domain-containing protein,taxID:1299321,902,MAGTENLPMIGLNFMPMSHIMGRGTLTSTLSTGGTGYFAASSDMST...
985,X8DWH6,unreviewed,Carboxylic acid reductase,taxID:1299321,1163,MTAGTAARVAKLFESDPQFRAAMPDPAVMDSLLAPGLRLSQVLHAL...

In [85]:
idx, values = filter_outliers(df_interpro['length'], return_idx = True)
df_filtered = df_interpro.iloc[idx]
df_filtered

,uniprot_id,is_reviewed,function,tax_id,length,sequence
0,A0A010YLP6,unreviewed,Carrier domain-containing protein,taxID:927661,1152,MTHTDQGDVTTVAERRALLLEQDEQFASAVPDDHVTALVRQPTMSL...
1,A0A024JSK2,unreviewed,Carboxylic acid reductase,taxID:47839,1188,MTTDMKRENGTNSTTKATPRERVAERIRRVEATDEQYRNAKPDQAL...
2,A0A024JWI0,unreviewed,Carboxylic acid reductase,taxID:47839,1162,MSTTTREERLERRIENLTATDPQFAAAKPDPAVVEALEQPGLQLPQ...
3,A0A024JZE3,unreviewed,Carboxylic acid reductase,taxID:47839,1165,MAFVGRSDVKDPGAQQDQWERLARRRERLYAEDAQFAATRPDEQIA...
4,A0A024JZE8,unreviewed,Carboxylic acid reductase,taxID:47839,1182,MTSGSLRDIHLAEPGDNRDERTAQRVAELFDNDPQFRAAAPLPDVI...
...,...,...,...,...,...,...
979,X0Q040,unreviewed,Carboxylic acid reductase,taxID:1219028,1175,MSTDIREERLARRIADLYANDRQFVAARPSEALTAAIEQPGLRLPQ...
980,X8A9W7;X8CDI5,unreviewed,Carboxylic acid reductase,taxID:1767;taxID:1299331,1188,MTDTVTDSGREQRLTERVEQLYANDPQFRAAAPSPEVTEAAHRAGL...
981,X8CEN6,unreviewed,Carboxylic acid reductase,taxID:1299331,1162,MAATDEQFRNAQPDLSLQQAARQPGLRLPQILELFVEGYADRPAVG...
983,X8DPU6,unreviewed,Carboxylic acid reductase,taxID:1299321,1183,MTIDATADNTKEARRQRLGDRVRRLFTEDEQFRAAKPDTAVDAAVA...
985,X8DWH6,unreviewed,Carboxylic acid reductase,taxID:1299321,1163,MTAGTAARVAKLFESDPQFRAAMPDPAVMDSLLAPGLRLSQVLHAL...

Load the PDB files of the CAR homologs by parsing the UniProt
--

In [88]:
import requests
import pandas as pd
import os
import time

from tqdm.notebook import tqdm
# ── Load data ──────────────────────────────────────────────────────────────────
# `df` is the deduplicated DataFrame from the previous step
# (uniprot_id column may hold comma-separated IDs that share the same sequence)
print(f"Total unique sequences: {len(df)}")
os.makedirs("structures", exist_ok=True)

def get_alphafold_pdb_url(uniprot_id: str) -> str:
    """
    Query AlphaFold EBI API to get the actual PDB download URL.
    The API returns metadata including 'pdbUrl' which points to the exact file.
    This avoids hardcoding version numbers (v1/v2/v3/v4).
    
    API endpoint: https://alphafold.ebi.ac.uk/api/prediction/{uniprot_id}
    """
    url = f"https://alphafold.ebi.ac.uk/api/prediction/{uniprot_id}"
    res = requests.get(url, timeout=10)
    if res.status_code != 200:
        return None
    data = res.json()
    if not data:
        return None
    return data[0].get("pdbUrl")

def download_structure(pdb_url: str, save_path: str) -> bool:
    """Download PDB file from a direct URL and save to disk."""
    res = requests.get(pdb_url, timeout=30)
    if res.status_code == 200:
        with open(save_path, "w") as f:
            f.write(res.text)
        return True
    return False

# ── Main loop ──────────────────────────────────────────────────────────────────
for ids_str in tqdm(df['uniprot_id']):
    uniprot_ids = ids_str.split(';')
    
    # Skip if any ID in this group already has a downloaded structure
    if any(os.path.exists(f"structures/car_{uid}.pdb") for uid in uniprot_ids):
        print(f"[SKIP]  {ids_str}")
        continue
    
    # Try each uniprot_id in order; stop at the first one that yields a structure
    success_uid = None
    for uid in uniprot_ids:
        pdb_url = get_alphafold_pdb_url(uid)
        if pdb_url and download_structure(pdb_url, f"structures/car_{uid}.pdb"):
            success_uid = uid
            break
        time.sleep(0.3)  # rate-limit between fallback attempts within a group
    
    if success_uid:
        tag = f"{success_uid}" + (f"  (from group of {len(uniprot_ids)})" if len(uniprot_ids) > 1 else "")
        print(f"[SUCCESS]    {tag}")
    else:
        print(f"[FAIL]  {ids_str} — no structure found for any ID")
    
    time.sleep(0.3)

Total unique sequences: 986

  0%|          | 0/986 [00:00<?, ?it/s]

[SKIP]  A0A010YLP6
[SKIP]  A0A024JSK2
[SKIP]  A0A024JWI0
[SKIP]  A0A024JZE3
[SKIP]  A0A024JZE8
[SUCCESS]    A0A045K2P5  (from group of 8)
[SKIP]  A0A051U3G5
[SKIP]  A0A051UFG9
[SKIP]  A0A064CG00
[SKIP]  A0A0B1ZH49
[SKIP]  A0A0B1ZIQ0
[SKIP]  A0A0B8NM02
[SKIP]  A0A0D1L7Y1
[SUCCESS]    A0A0D1LMF4
[SUCCESS]    A0A0D2EWW5
[SUCCESS]    A0A0E4CLA0
[SUCCESS]    A0A0E4GX90
[SUCCESS]    A0A0F4ES51
[SUCCESS]    A0A0F5MSZ2
[SUCCESS]    A0A0F5NA60
[SUCCESS]    A0A0H2ZUI5
[SUCCESS]    A0A0H3MCY6  (from group of 2)
[SUCCESS]    A0A0H3MU55  (from group of 3)
[SUCCESS]    A0A0H5BB76
[SUCCESS]    A0A0H5NNV9
[SUCCESS]    A0A0H5RL48
[SUCCESS]    A0A0H5RMP7
[SUCCESS]    A0A0I9Z3I8
[SUCCESS]    A0A0J6VW20
[SUCCESS]    A0A0J6VZP7
[SUCCESS]    A0A0J6WR15
[SUCCESS]    A0A0J6Z0M9
[SUCCESS]    A0A0J8TWL2  (from group of 2)
[SUCCESS]    A0A0J8TXD9
[SUCCESS]    A0A0K0X557
[SUCCESS]    A0A0K0XB28
[SUCCESS]    A0A0K0XCM7
[SUCCESS]    A0A0L0JLL3
[SUCCESS]    A0A0L0JTI1
[SUCCESS]    A0A0M2JYX2
[SUCCESS]    A0A0M2WG04
[SUCCESS]    A0A0N9XFV2
[SUCCESS]    A0A0N9YG13
[SUCCESS]    A0A0Q2M080
[SUCCESS]    A0A0Q2RTZ0
[SUCCESS]    A0A0U0WCI8  (from group of 2)
[SUCCESS]    A0A0U0ZG49
[SUCCESS]    A0A0U0ZGC0
[SUCCESS]    A0A0U0ZLV7
[SUCCESS]    A0A0U0ZPX5
[SUCCESS]    A0A0U1D4T9
[SUCCESS]    A0A0U1DUP4
[SUCCESS]    A0A0U1E1C0
[SUCCESS]    A0A0U1Z2H3
[SUCCESS]    A0A100W5H8
[SUCCESS]    A0A100W5I0
[SUCCESS]    A0A100WJQ5
[SUCCESS]    A0A100WL29
[SUCCESS]    A0A100WRZ4
[SUCCESS]    A0A117I9B3
[SUCCESS]    A0A117I9Z0
[SUCCESS]    A0A117IEQ2
[SUCCESS]    A0A124DZH3
[SUCCESS]    A0A132PRD2
[SUCCESS]    A0A132PS78
[FAIL]  A0A137ZRE2 — no structure found for any ID
[SUCCESS]    A0A138AE52
[SUCCESS]    A0A143QSN8
[SUCCESS]    A0A147DRP6
[SUCCESS]    A0A154V3B3
[SUCCESS]    A0A163Z098
[SUCCESS]    A0A164L8S1
[SUCCESS]    A0A164L8T1
[SUCCESS]    A0A172UHW8
[FAIL]  A0A177F334 — no structure found for any ID
[SUCCESS]    A0A177XU71
[SUCCESS]    A0A178CV43
[SUCCESS]    A0A178LTI6
[SUCCESS]    A0A179V396
[SUCCESS]    A0A179V451
[SUCCESS]    A0A179VA95
[SUCCESS]    A0A179VCR2
[SUCCESS]    A0A1A0MX32
[SUCCESS]    A0A1A0MY20
[SUCCESS]    A0A1A0QWX6
[SUCCESS]    A0A1A0RF23
[SUCCESS]    A0A1A0RF29
[SUCCESS]    A0A1A0V6S5
[SUCCESS]    A0A1A0VBY7
[SUCCESS]    A0A1A0VEQ6
[SUCCESS]    A0A1A0VUX0
[SUCCESS]    A0A1A0VZR1
[SUCCESS]    A0A1A0W2R1
[SUCCESS]    A0A1A0WCC8
[SUCCESS]    A0A1A1WCA4
[SUCCESS]    A0A1A1WCB1
[SUCCESS]    A0A1A2DP38
[SUCCESS]    A0A1A2EVY2
[SUCCESS]    A0A1A2NZX0
[SUCCESS]    A0A1A2P0A6
[SUCCESS]    A0A1A2SD60
[SUCCESS]    A0A1A2SGC1
[SUCCESS]    A0A1A2SKN5
[SUCCESS]    A0A1A2SQA4
[SUCCESS]    A0A1A2STK0
[SUCCESS]    A0A1A2UBP1
[SUCCESS]    A0A1A2VM45
[SUCCESS]    A0A1A2YRQ4
[SUCCESS]    A0A1A2YVQ7
[SUCCESS]    A0A1A2YYV5
[SUCCESS]    A0A1A2Z2J8
[SUCCESS]    A0A1A2Z8H6
[SUCCESS]    A0A1A2ZG36
[SUCCESS]    A0A1A3BEU1
[SUCCESS]    A0A1A3BWY5
[SUCCESS]    A0A1A3C4T0
[SUCCESS]    A0A1A3GZZ6
[SUCCESS]    A0A1A3H185
[SUCCESS]    A0A1A3KI76
[SUCCESS]    A0A1A3KJV4
[SUCCESS]    A0A1A3KPW7
[SUCCESS]    A0A1A3N5H1
[SUCCESS]    A0A1A3N7A1
[SUCCESS]    A0A1A3NWI0
[SUCCESS]    A0A1A3P195
[SUCCESS]    A0A1A3P7V6
[SUCCESS]    A0A1A3TXF6
[SUCCESS]    A0A1A3U111
[SUCCESS]    A0A1A3U7T4
[SUCCESS]    A0A1A6BMZ1
[SUCCESS]    A0A1B2HUS2
[SUCCESS]    A0A1B4Y4X4
[SUCCESS]    A0A1B8SKL4
[SUCCESS]    A0A1B9CJD7
[SUCCESS]    A0A1B9CX42
[SUCCESS]    A0A1D7VWY6
[SUCCESS]    A0A1D8GAR9
[SUCCESS]    A0A1E3RBW0
[SUCCESS]    A0A1E3S0K4
[SUCCESS]    A0A1E3S739
[SUCCESS]    A0A1E3SKI4
[SUCCESS]    A0A1E3SLH6
[SUCCESS]    A0A1E3SN70
[SUCCESS]    A0A1E3SV84
[SUCCESS]    A0A1E5P3C7
[SUCCESS]    A0A1E7JQU2
[SUCCESS]    A0A1E7L3V6
[SUCCESS]    A0A1E8Q6I1
[SUCCESS]    A0A1E8QAA5
[SUCCESS]    A0A1G4V447
[SUCCESS]    A0A1G4WIS5
[SUCCESS]    A0A1G4WIS9
[SUCCESS]    A0A1G6K7R0
[SUCCESS]    A0A1G6PJB6
[SUCCESS]    A0A1G7L4S3
[SUCCESS]    A0A1G9S8F3
[SUCCESS]    A0A1H0URB3
[SUCCESS]    A0A1H1DDV3
[SUCCESS]    A0A1H4QLQ0
[SUCCESS]    A0A1H6J6E6
[SUCCESS]    A0A1H6L3W8
[SUCCESS]    A0A1H7CJ42
[SUCCESS]    A0A1H8UHI3
[SUCCESS]    A0A1H9X129
[SUCCESS]    A0A1I0U7E5
[SUCCESS]    A0A1I5LZY6
[SUCCESS]    A0A1I6DEK9
[SUCCESS]    A0A1I6TMF1
[SUCCESS]    A0A1J0VT15
[SUCCESS]    A0A1N7EPZ8
[SUCCESS]    A0A1Q4H4E6
[SUCCESS]    A0A1Q4HNQ9
[SUCCESS]    A0A1Q4HPF1
[SUCCESS]    A0A1Q9LN00
[SUCCESS]    A0A1Q9LN36
[SUCCESS]    A0A1Q9W8K3
[SUCCESS]    A0A1R3Y1N0
[SUCCESS]    A0A1S1KKY6
[SUCCESS]    A0A1S1KYS6
[SUCCESS]    A0A1S1L5R7
[SUCCESS]    A0A1S1L7L3
[SUCCESS]    A0A1S1LBB7
[SUCCESS]    A0A1S1LF81
[SUCCESS]    A0A1S1LFP5
[SUCCESS]    A0A1S1LPM2
[SUCCESS]    A0A1S1LSR7
[SUCCESS]    A0A1S1LZ61
[SUCCESS]    A0A1S1M3C1
[SUCCESS]    A0A1S1M770
[SUCCESS]    A0A1S1M9C0
[SUCCESS]    A0A1S1MVI3
[SUCCESS]    A0A1S1NIB3
[SUCCESS]    A0A1T3NLC9
[SUCCESS]    A0A1T3NUL4
[SUCCESS]    A0A1T3WDZ1
[SUCCESS]    A0A1T5FEL0
[SUCCESS]    A0A1T5FV39
[SUCCESS]    A0A1T5XJ36
[SUCCESS]    A0A1T7HTT5
[SUCCESS]    A0A1U3MWT7
[SUCCESS]    A0A1U9QLV6
[FAIL]  A0A1V2I487 — no structure found for any ID
[FAIL]  A0A1V2IEY4 — no structure found for any ID
[SUCCESS]    A0A1V3WG34  (from group of 3)
[SUCCESS]    A0A1W9YPH5
[SUCCESS]    A0A1W9Z9K2
[SUCCESS]    A0A1W9Z9K6
[SUCCESS]    A0A1W9ZC84
[SUCCESS]    A0A1W9ZN90
[SUCCESS]    A0A1W9ZSJ9
[SUCCESS]    A0A1W9ZU79
[SUCCESS]    A0A1X0A2U5
[SUCCESS]    A0A1X0AYB7
[SUCCESS]    A0A1X0AZ01
[SUCCESS]    A0A1X0BWL6
[SUCCESS]    A0A1X0D333
[SUCCESS]    A0A1X0DSG2
[SUCCESS]    A0A1X0DT32
[SUCCESS]    A0A1X0ED97
[SUCCESS]    A0A1X0FY05
[SUCCESS]    A0A1X0FZ49
[SUCCESS]    A0A1X0I595
[SUCCESS]    A0A1X0I7R5
[SUCCESS]    A0A1X0INU7
[SUCCESS]    A0A1X0IRY1
[SUCCESS]    A0A1X0J5R4
[SUCCESS]    A0A1X0J866
[SUCCESS]    A0A1X0K0U7
[SUCCESS]    A0A1X0KKW9
[SUCCESS]    A0A1X0XWA4
[SUCCESS]    A0A1X0XYW4
[SUCCESS]    A0A1X0Y567
[SUCCESS]    A0A1X0YC10
[SUCCESS]    A0A1X1RGM6
[SUCCESS]    A0A1X1RMT2
[SUCCESS]    A0A1X1RT79
[SUCCESS]    A0A1X1SSG1
[SUCCESS]    A0A1X1SXX1
[SUCCESS]    A0A1X1TAZ5
[SUCCESS]    A0A1X1TV41
[SUCCESS]    A0A1X1TX55
[SUCCESS]    A0A1X1TXE9
[SUCCESS]    A0A1X1U567
[SUCCESS]    A0A1X1U6G3
[SUCCESS]    A0A1X1V443
[SUCCESS]    A0A1X1VXW9
[SUCCESS]    A0A1X1WD57
[SUCCESS]    A0A1X1XH13
[SUCCESS]    A0A1X1XQZ1
[SUCCESS]    A0A1X1Y0D8
[SUCCESS]    A0A1X1YHA8
[SUCCESS]    A0A1X1YTK3
[SUCCESS]    A0A1X1Z1D7
[SUCCESS]    A0A1X1ZAJ3
[SUCCESS]    A0A1X1ZUN6
[SUCCESS]    A0A1X2AMC4
[SUCCESS]    A0A1X2DGR4
[SUCCESS]    A0A1X2DIF1
[SUCCESS]    A0A1X2DPB1
[SUCCESS]    A0A1X2EPB4
[SUCCESS]    A0A1X2F2L6
[SUCCESS]    A0A1X2FK51
[SUCCESS]    A0A1X2FLH9
[SUCCESS]    A0A1X2KZQ2
[SUCCESS]    A0A1X2L0G7
[SUCCESS]    A0A1X2LPX9
[SUCCESS]    A0A1X2LYL0
[SUCCESS]    A0A1Y0C436
[SUCCESS]    A0A1Y0C5T9
[SUCCESS]    A0A1Y0CFN4
[SUCCESS]    A0A1Y2NRV5
[SUCCESS]    A0A1Y5PCF7
[SUCCESS]    A0A1Y5Y6P3
[SUCCESS]    A0A1Z4EBS9
[SUCCESS]    A0A1Z4EGK3
[SUCCESS]    A0A1Z4EZ40
[SUCCESS]    A0A1Z4EZ73
[SUCCESS]    A0A1Z4F080
[SUCCESS]    A0A1Z4F4H3
[SUCCESS]    A0A231H7W5
[SUCCESS]    A0A251Y3Z3
[SUCCESS]    A0A255DTC1
[SUCCESS]    A0A266LQ04
[SUCCESS]    A0A285LZS8
[SUCCESS]    A0A286MPQ6
[SUCCESS]    A0A291RHD9
[SUCCESS]    A0A291RHE0
[SUCCESS]    A0A291RWF7
[SUCCESS]    A0A2A2ZGB2  (from group of 2)
[SUCCESS]    A0A2A3LDA8
[SUCCESS]    A0A2A7NAH8
[SUCCESS]    A0A2A7NH78
[SUCCESS]    A0A2A9FBQ2
[SUCCESS]    A0A2G5PCS5
[SUCCESS]    A0A2G5PN19
[SUCCESS]    A0A2G8B7A9
[SUCCESS]    A0A2I2L057
[SUCCESS]    A0A2K4Y436
[SUCCESS]    A0A2K4Y9B3
[SUCCESS]    A0A2K4YB08
[SUCCESS]    A0A2K4YB80
[SUCCESS]    A0A2N3VL42
[SUCCESS]    A0A2N8P9Q2
[SUCCESS]    A0A2N8PI87
[SUCCESS]    A0A2P2GSN2
[SUCCESS]    A0A2P8I1A3
[SUCCESS]    A0A2S6AAE1
[SUCCESS]    A0A2S8BEG5
[SUCCESS]    A0A2S8BGN3
[SUCCESS]    A0A2T2Z8U3
[SUCCESS]    A0A2U3N8I6
[SUCCESS]    A0A2U3NPT1
[SUCCESS]    A0A2U3P0N3
[SUCCESS]    A0A2U3P697
[SUCCESS]    A0A2U3PHP0
[SUCCESS]    A0A2U9PQ99
[SUCCESS]    A0A2U9PXP1
[SUCCESS]    A0A317N4Q8
[SUCCESS]    A0A318HI90
[FAIL]  A0A318HK00 — no structure found for any ID
[SUCCESS]    A0A318JQK2
[SUCCESS]    A0A318JYA7
[SUCCESS]    A0A318K9K9
[SUCCESS]    A0A329K2Y4
[SUCCESS]    A0A329KGE0
[SUCCESS]    A0A329KUN3
[SUCCESS]    A0A329LAU5
[SUCCESS]    A0A329M492
[SUCCESS]    A0A345I2A9
[SUCCESS]    A0A370HAX8
[SUCCESS]    A0A370HBB6
[SUCCESS]    A0A370I000
[SUCCESS]    A0A370I008
[SUCCESS]    A0A373A3G8
[SUCCESS]    A0A373A520
[SUCCESS]    A0A375YKM9
[SUCCESS]    A0A375Z3F8
[SUCCESS]    A0A378T271
[SUCCESS]    A0A378T283
[SUCCESS]    A0A378TAR8
[SUCCESS]    A0A378UBH7
[SUCCESS]    A0A378WN66
[SUCCESS]    A0A378YSF8
[SUCCESS]    A0A386ZPG1
[SUCCESS]    A0A3A4K4S5
[SUCCESS]    A0A3B0ALY4
[SUCCESS]    A0A3E0HEA4
[SUCCESS]    A0A3E1HFK0
[FAIL]  A0A3E2MQN5 — no structure found for any ID
[SUCCESS]    A0A3M2L4P9
[SUCCESS]    A0A3M2LDY9
[SUCCESS]    A0A3P8LHL6
[SUCCESS]    A0A3Q9KMK0
[SUCCESS]    A0A3S3ZSH2
[SUCCESS]    A0A3S4RS92
[SUCCESS]    A0A401VU54
[SUCCESS]    A0A401VU81
[SUCCESS]    A0A401YDY7
[SUCCESS]    A0A401YST3
[SUCCESS]    A0A419HML1
[SUCCESS]    A0A421AW77
[SUCCESS]    A0A426SF14
[SUCCESS]    A0A438ATK5
[SUCCESS]    A0A438AUV2
[SUCCESS]    A0A447GD36
[SUCCESS]    A0A449GAD2
[SUCCESS]    A0A498PZU2
[SUCCESS]    A0A498PZZ1
[SUCCESS]    A0A498QQD7
[SUCCESS]    A0A4P6Q8L8
[SUCCESS]    A0A4Q7KNW3
[SUCCESS]    A0A4Q9HZT3
[SUCCESS]    A0A4R1FSR2
[SUCCESS]    A0A4R1FWD7
[SUCCESS]    A0A4R4V2D0
[SUCCESS]    A0A4R5PD40
[SUCCESS]    A0A4R5PF75
[SUCCESS]    A0A4R5WK74
[SUCCESS]    A0A4R5WKD4
[SUCCESS]    A0A4R5X5Y0
[SUCCESS]    A0A4R6P566
[SUCCESS]    A0A4R7IZC0
[SUCCESS]    A0A4R8R2S8
[SUCCESS]    A0A4R8S1E2
[SUCCESS]    A0A4R8S1L2
[SUCCESS]    A0A4R8S6S5
[SUCCESS]    A0A4R8S7U6
[SUCCESS]    A0A4R8S8U4
[SUCCESS]    A0A4R8SET2
[SUCCESS]    A0A4R8SIE9
[SUCCESS]    A0A4R8T0X1
[SUCCESS]    A0A4U8W070
[SUCCESS]    A0A4V3HUY3
[SUCCESS]    A0A4V3I141
[SUCCESS]    A0A4Z0HM23
[SUCCESS]    A0A4Z0HRY8
[SUCCESS]    A0A4Z0HSE6
[SUCCESS]    A0A4Z0LXD8
[SUCCESS]    A0A502EC16
[SUCCESS]    A0A511M4D4
[SUCCESS]    A0A516NPD0
[SUCCESS]    A0A542DCL6
[SUCCESS]    A0A542XQI9
[SUCCESS]    A0A543EXG0
[SUCCESS]    A0A543JAT3
[SUCCESS]    A0A544W0X3
[SUCCESS]    A0A544W3Y3
[SUCCESS]    A0A544W498
[SUCCESS]    A0A557XZJ5
[SUCCESS]    A0A561TWL9
[SUCCESS]    A0A5B1BH70
[SUCCESS]    A0A5C5R6E0
[SUCCESS]    A0A5C5RJE3
[SUCCESS]    A0A5C5RYF1  (from group of 2)
[SUCCESS]    A0A5C7XWH5
[SUCCESS]    A0A5C7YBR3
[SUCCESS]    A0A5J4LNN8
[SUCCESS]    A0A5J5JW77
[SUCCESS]    A0A5N0E0J5
[SUCCESS]    A0A5N0EJT8
[SUCCESS]    A0A5N0UWA7
[SUCCESS]    A0A5N5VEC4
[SUCCESS]    A0A5Q5BJ80  (from group of 2)
[SUCCESS]    A0A5Q5CFF7
[SUCCESS]    A0A5R8NPV3
[SUCCESS]    A0A5R8PAY8
[SUCCESS]    A0A5R8YUR2  (from group of 2)
[SUCCESS]    A0A5S9NMT1
[SUCCESS]    A0A640SD75
[SUCCESS]    A0A640SQP3
[SUCCESS]    A0A640UJM0
[SUCCESS]    A0A653EJG9
[SUCCESS]    A0A653FAQ0  (from group of 3)
[SUCCESS]    A0A653FCI4  (from group of 2)
[SUCCESS]    A0A653FIK1
[SUCCESS]    A0A6A0AQ11
[SUCCESS]    A0A6G3SLA6
[SUCCESS]    A0A6G4AHJ1
[SUCCESS]    A0A6G9H9S9
[SUCCESS]    A0A6G9XS88
[SUCCESS]    A0A6G9XT36
[SUCCESS]    A0A6G9YM63
[SUCCESS]    A0A6G9YNU3
[SUCCESS]    A0A6G9Z057
[SUCCESS]    A0A6G9Z0E6
[SUCCESS]    A0A6G9Z2E5
[SUCCESS]    A0A6G9ZF28
[SUCCESS]    A0A6H0S7C9
[SUCCESS]    A0A6H9YKW3
[SUCCESS]    A0A6I3L2J0
[SUCCESS]    A0A6I4MRE2
[SUCCESS]    A0A6J5A950
[SUCCESS]    A0A6N4URH6
[SUCCESS]    A0A6N4VDZ9
[SUCCESS]    A0A6N4W3I8
[SUCCESS]    A0A6N4W768
[SUCCESS]    A0A6P1CTQ2
[SUCCESS]    A0A6P1D575
[SUCCESS]    A0A6S6NYQ7
[SUCCESS]    A0A6S6P6D8
[SUCCESS]    A0A7D6E1I6
[SUCCESS]    A0A7D6ZHA2
[SUCCESS]    A0A7G1KQI6
[SUCCESS]    A0A7G8PBZ5
[SUCCESS]    A0A7G8PH04
[SUCCESS]    A0A7G8PH05
[SUCCESS]    A0A7H0I6F1
[SUCCESS]    A0A7H0IEA3
[SUCCESS]    A0A7H1Q5K4
[SUCCESS]    A0A7I7JNU6
[SUCCESS]    A0A7I7KQ88
[SUCCESS]    A0A7I7LJC3
[SUCCESS]    A0A7I7MEC1
[SUCCESS]    A0A7I7MPF4
[SUCCESS]    A0A7I7NVN0
[SUCCESS]    A0A7I7P449
[SUCCESS]    A0A7I7PH49
[SUCCESS]    A0A7I7PIE9
[SUCCESS]    A0A7I7Q331
[SUCCESS]    A0A7I7Q4Z2
[SUCCESS]    A0A7I7QB07
[SUCCESS]    A0A7I7QL20
[SUCCESS]    A0A7I7QP40
[SUCCESS]    A0A7I7QP46
[SUCCESS]    A0A7I7R3J2
[SUCCESS]    A0A7I7RRZ6
[SUCCESS]    A0A7I7RS79
[SUCCESS]    A0A7I7RUI0
[SUCCESS]    A0A7I7RZ78
[SUCCESS]    A0A7I7S1X3
[SUCCESS]    A0A7I7SCY4
[SUCCESS]    A0A7I7SXJ5
[SUCCESS]    A0A7I7TD11
[SUCCESS]    A0A7I7UBW3
[SUCCESS]    A0A7I7VZ71
[SUCCESS]    A0A7I7WCE0
[SUCCESS]    A0A7I7WJN8
[SUCCESS]    A0A7I7X9D1
[SUCCESS]    A0A7I7X9S1
[SUCCESS]    A0A7I7X9S2
[SUCCESS]    A0A7I7XP41
[SUCCESS]    A0A7I7XXG0
[SUCCESS]    A0A7I7YUU0
[SUCCESS]    A0A7I7YXB1
[SUCCESS]    A0A7I7ZRH7
[SUCCESS]    A0A7I9W165
[SUCCESS]    A0A7I9WQZ1
[SUCCESS]    A0A7I9XMW5
[SUCCESS]    A0A7I9Y2B3
[SUCCESS]    A0A7I9YES0
[SUCCESS]    A0A7I9YMY6
[SUCCESS]    A0A7I9YZ18
[SUCCESS]    A0A7I9Z5A6
[SUCCESS]    A0A7I9Z705
[SUCCESS]    A0A7I9ZAR1
[SUCCESS]    A0A7I9ZCH7
[SUCCESS]    A0A7I9ZRY4
[SUCCESS]    A0A7K0D4H1
[SUCCESS]    A0A7K0DM07
[SUCCESS]    A0A7K1VB93
[SUCCESS]    A0A7K3LE40
[SUCCESS]    A0A7K3R588
[SUCCESS]    A0A7R7MY24
[SUCCESS]    A0A7R7RPY0
[SUCCESS]    A0A7T1TD85
[SUCCESS]    A0A7U5MR51
[SUCCESS]    A0A7U5RWM8
[SUCCESS]    A0A7U5RXC1
[SUCCESS]    A0A7U9L3B0
[SUCCESS]    A0A7U9Q384
[SUCCESS]    A0A7V8LNU0
[SUCCESS]    A0A7V8RXZ3
[SUCCESS]    A0A7V8RXZ7
[SUCCESS]    A0A7V8RYM6
[SUCCESS]    A0A7W6BWA9
[SUCCESS]    A0A7W6FYK5
[SUCCESS]    A0A7W7G0Z9
[SUCCESS]    A0A7W7VZ67
[SUCCESS]    A0A7W8BW88
[SUCCESS]    A0A7W9NKR9
[SUCCESS]    A0A7W9PLQ8
[SUCCESS]    A0A7X5R533
[SUCCESS]    A0A7X5TUU1
[SUCCESS]    A0A7X6M5C6
[SUCCESS]    A0A7X6MIZ0
[SUCCESS]    A0A7X6MKH2
[SUCCESS]    A0A7X6R1D2
[SUCCESS]    A0A7Y9XV54
[SUCCESS]    A0A7Z0IKF1
[SUCCESS]    A0A7Z7ILT5
[SUCCESS]    A0A829HQL8  (from group of 2)
[SUCCESS]    A0A829HTG5  (from group of 3)
[SUCCESS]    A0A829HWH3
[SUCCESS]    A0A829MDQ7  (from group of 2)
[SUCCESS]    A0A829MIB4  (from group of 2)
[SUCCESS]    A0A829PKA2
[SUCCESS]    A0A829PS24
[SUCCESS]    A0A829PS58
[SUCCESS]    A0A829PSZ5
[SUCCESS]    A0A829PY25  (from group of 2)
[SUCCESS]    A0A829Q102
[SUCCESS]    A0A829Q1V2  (from group of 2)
[SUCCESS]    A0A829Q576
[SUCCESS]    A0A829QF13  (from group of 3)
[SUCCESS]    A0A829QG83  (from group of 2)
[SUCCESS]    A0A829QKT7
[SUCCESS]    A0A839Q3V9
[SUCCESS]    A0A840Q103
[SUCCESS]    A0A846MH08
[SUCCESS]    A0A846VZQ1
[SUCCESS]    A0A846WXM5
[SUCCESS]    A0A846XPH2
[SUCCESS]    A0A846XYC4
[SUCCESS]    A0A846YJB4
[SUCCESS]    A0A848KDK6
[SUCCESS]    A0A849CGR7
[SUCCESS]    A0A850PMX4
[SUCCESS]    A0A853LX37
[SUCCESS]    A0A853LXB5
[SUCCESS]    A0A853LYQ8
[SUCCESS]    A0A853M2B7
[SUCCESS]    A0A8E2LPD0
[SUCCESS]    A0A8H2PI19
[SUCCESS]    A0A8H2PIF1
[SUCCESS]    A0A8J3FU84
[SUCCESS]    A0A8J4A7U7
[SUCCESS]    A0A917FVC2
[SUCCESS]    A0A917Q703
[SUCCESS]    A0A917RUF6
[SUCCESS]    A0A918CWM2
[SUCCESS]    A0A918EZ18
[SUCCESS]    A0A919J5R3
[SUCCESS]    A0A927EY10
[SUCCESS]    A0A927JBF8
[SUCCESS]    A0A927MND6
[SUCCESS]    A0A934NT38
[SUCCESS]    A0A937RSP3
[SUCCESS]    A0A939FJS2
[SUCCESS]    A0A975JWU9
[SUCCESS]    A0A9N7QL79
[SUCCESS]    A0A9N7QNJ2
[SUCCESS]    A0A9P3UYS2
[SUCCESS]    A0A9Q7SE40
[SUCCESS]    A0A9Q7SI49
[SUCCESS]    A0A9Q7WGW0
[SUCCESS]    A0A9Q7WIY4
[SUCCESS]    A0A9W4AZG8
[SUCCESS]    A0A9X2E3D3
[SUCCESS]    A0A9X2E3I2
[SUCCESS]    A0A9X2E4R0
[SUCCESS]    A0A9X2VIG8
[SUCCESS]    A0A9X2YIQ0
[SUCCESS]    A0A9X2YRI8
[SUCCESS]    A0A9X2Z2J6
[SUCCESS]    A0A9X3BRH0
[SUCCESS]    A0A9X3C2T0
[SUCCESS]    A0A9X7ILG2
[SUCCESS]    A0A9X7JMG6
[SUCCESS]    A0A9X7WHR6
[SUCCESS]    A0A9X8QWT3
[SUCCESS]    A0A9X8QZ54
[SUCCESS]    A0A9Y2IBK6
[SUCCESS]    A0A9Y2N0A1
[SUCCESS]    A0AA37PJ36
[SUCCESS]    A0AA37PJQ2
[SUCCESS]    A0AA37PNY0
[SUCCESS]    A0AA37PRM7
[SUCCESS]    A0AA42BYT1
[SUCCESS]    A0AA90NQ91
[SUCCESS]    A0AA91EXD2
[SUCCESS]    A0AA91M3B5
[SUCCESS]    A0AA94UBA0
[SUCCESS]    A0AAC9VV50
[SUCCESS]    A0AAC9YL18
[SUCCESS]    A0AAC9YPU9
[SUCCESS]    A0AAD1H459
[SUCCESS]    A0AAD1HCQ5
[SUCCESS]    A0AAD1HL52
[SUCCESS]    A0AAD1I0L4
[SUCCESS]    A0AAD1I1H5
[SUCCESS]    A0AAD1IMP5
[SUCCESS]    A0AAD1IMS5
[SUCCESS]    A0AAD1MYY6
[SUCCESS]    A0AAE4RDM5
[SUCCESS]    A0AAE4UCZ3
[SUCCESS]    A0AAE4UD82
[SUCCESS]    A0AAE4VIV1
[SUCCESS]    A0AAE6TQG2
[SUCCESS]    A0AAE6XNC3
[SUCCESS]    A0AAI8TZQ7
[SUCCESS]    A0AAI8U017
[SUCCESS]    A0AAJ1W4G5
[SUCCESS]    A0AAJ3NLH7
[SUCCESS]    A0AAJ3NT49
[SUCCESS]    A0AAJ3TVZ5
[SUCCESS]    A0AAP6BDL8
[SUCCESS]    A0AAU4K3W1
[SUCCESS]    A0AAV2WH99
[SUCCESS]    A0AAW5S5J5
[SUCCESS]    A0AAW5SKH5
[SUCCESS]    A0AAW5TB85
[SUCCESS]    A0AAW5TB97
[SUCCESS]    A0AAW5THR0
[SUCCESS]    A0AAX1J9Y8
[SUCCESS]    A0AAX1JCS8
[SUCCESS]    A0AAX1JED5
[SUCCESS]    A0AAX1JEG7
[SUCCESS]    A0AAX2ZQB8
[SUCCESS]    A0AAX2ZQD4
[SUCCESS]    A0AAX3A495
[SUCCESS]    A0AB33ACF4
[SUCCESS]    A0AB33ACN0
[SUCCESS]    A0AB33ADN5
[SUCCESS]    A0AB33AHW7
[SUCCESS]    A0AB33TCW4
[SUCCESS]    A0AB33TD28  (from group of 2)
[SUCCESS]    A0AB38CYE9
[SUCCESS]    A0AB38CZ04
[SUCCESS]    A0AB38D5A4
[SUCCESS]    A0AB38USB2
[SUCCESS]    A0AB72XQA2  (from group of 2)
[SUCCESS]    A0AB73LE91
[SUCCESS]    A0AB73LM64
[SUCCESS]    A0AB73MHS4
[SUCCESS]    A0AB73N8J1
[SUCCESS]    A0AB73U2P7
[SUCCESS]    A0AB73U621
[SUCCESS]    A0AB73U7U3
[SUCCESS]    A0AB73U9A3
[SUCCESS]    A0AB74F9U6  (from group of 2)
[SUCCESS]    A0AB74FEB0
[SUCCESS]    A0AB74FGQ8  (from group of 3)
[SUCCESS]    A0ABD6NXB6
[SUCCESS]    A0ABD6QL27
[SUCCESS]    A0ABD6QS80
[SUCCESS]    A0ABD7HFI6
[SUCCESS]    A0ABD7HHW4
[SUCCESS]    A0ABD7HN08
[SUCCESS]    A0ABF7PG24
[FAIL]  A0ABM7I197 — no structure found for any ID
[FAIL]  A0ABM7J8Q1 — no structure found for any ID
[FAIL]  A0ABM7JWD3 — no structure found for any ID
[FAIL]  A0ABM7K1P0 — no structure found for any ID
[FAIL]  A0ABM7SIW3 — no structure found for any ID
[FAIL]  A0ABM7SN96 — no structure found for any ID
[FAIL]  A0ABM7SX73 — no structure found for any ID
[FAIL]  A0ABM9LWN3 — no structure found for any ID
[FAIL]  A0ABN0UMW0 — no structure found for any ID
[FAIL]  A0ABN0UZZ3 — no structure found for any ID
[FAIL]  A0ABN1T3W5 — no structure found for any ID
[FAIL]  A0ABN1UVC2 — no structure found for any ID
[FAIL]  A0ABN2Q9Z6 — no structure found for any ID
[FAIL]  A0ABN3F4Q3 — no structure found for any ID
[FAIL]  A0ABN3KZK6;A0ABP8T118 — no structure found for any ID
[FAIL]  A0ABN5YF31 — no structure found for any ID
[FAIL]  A0ABN5YVZ6 — no structure found for any ID
[FAIL]  A0ABN5YWL7 — no structure found for any ID
[FAIL]  A0ABN5ZG94 — no structure found for any ID
[FAIL]  A0ABN5ZR55 — no structure found for any ID
[FAIL]  A0ABN5ZWQ7 — no structure found for any ID
[FAIL]  A0ABN6AMT8 — no structure found for any ID
[FAIL]  A0ABN6AP09 — no structure found for any ID
[FAIL]  A0ABN6IEF7 — no structure found for any ID
[FAIL]  A0ABN6IL17 — no structure found for any ID
[FAIL]  A0ABN6U5V0 — no structure found for any ID
[FAIL]  A0ABN9NWH6 — no structure found for any ID
[FAIL]  A0ABP6G281 — no structure found for any ID
[FAIL]  A0ABP6W264 — no structure found for any ID
[FAIL]  A0ABP7F641 — no structure found for any ID
[FAIL]  A0ABP7FLY8 — no structure found for any ID
[FAIL]  A0ABP8EZM2 — no structure found for any ID
[FAIL]  A0ABP8RAE2 — no structure found for any ID
[FAIL]  A0ABP9K210 — no structure found for any ID
[FAIL]  A0ABQ1BG63 — no structure found for any ID
[FAIL]  A0ABQ1C2G9 — no structure found for any ID
[FAIL]  A0ABQ1CET0 — no structure found for any ID
[FAIL]  A0ABQ1V3W2 — no structure found for any ID
[FAIL]  A0ABQ2KKB0 — no structure found for any ID
[FAIL]  A0ABQ3A4P7 — no structure found for any ID
[FAIL]  A0ABQ3M7W9 — no structure found for any ID
[FAIL]  A0ABQ3MHH6 — no structure found for any ID
[FAIL]  A0ABQ3SCS9 — no structure found for any ID
[FAIL]  A0ABQ4FMS5 — no structure found for any ID
[FAIL]  A0ABQ6A4B6 — no structure found for any ID
[FAIL]  A0ABQ6XQ02 — no structure found for any ID
[FAIL]  A0ABR4YVY6 — no structure found for any ID
[FAIL]  A0ABR4YVZ6 — no structure found for any ID
[FAIL]  A0ABR4ZAR7 — no structure found for any ID
[FAIL]  A0ABR4ZEC0 — no structure found for any ID
[FAIL]  A0ABR5FFS4 — no structure found for any ID
[FAIL]  A0ABR5FS25 — no structure found for any ID